WAppActionResults/Controllers/ExcelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WAppActionResults.Utils.ActionResults;

namespace WAppActionResults.Controllers
{
    public class ExcelController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]//[HttpPost]
        public async Task<ActionResult> GenerateExcel()
        {
            var guid = Guid.NewGuid().ToString();
            var list = new[] {
                new { Name="Juan", Age=32, Email="juan@server.com", Date = DateTime.Today },
                new { Name="Jose", Age=22, Email="jose@server.com", Date = DateTime.Today.AddMonths(-3) },
                new { Name="Michael", Age=52, Email="michael@server.com", Date = DateTime.Today.AddYears(-23) },
                new { Name="Arturo", Age=32, Email="art@server.com", Date = DateTime.Today.AddYears(-34) },
            };

            //await Task.Delay(5000);
            //TempData[guid] = ExcelResult.Generar(list, "excel");
            //return Json(new { Guid = guid });

            return new ExcelResult("excel", list);
        }
    }
}

WAppActionResults/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WAppActionResults.Utils.ActionResults;

namespace WAppActionResults.Controllers
{
    public class Persona
    {
        public string Nombre { get; set; }
    }

    //https://msdn.microsoft.com/en-us/library/system.web.mvc.actionresult(v=vs.118).aspx
    //https://developer.mozilla.org/es/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Lista_completa_de_tipos_MIME

    public class HomeController : Controller
    {
        //EJEMPLO 0:
        //public ActionResult Index()
        //{
        //    return new EmptyResult();
        //    return Empty();  
        //}

        //EJEMPLO 1: POr defecto se devuelve un ContentResult
        //public Persona Index()
        //{
        //    return DateTime.Now.Second;
        //}

        //EJEMPLO 1.1: POr defecto se devuelve un ContentResult
        //public Persona Index()
        //{
        //    return new Persona { Nombre = "Michael Emir" };
        //}

        //EJEMPLO 2:
        //public ActionResult Index()
        //{
        //    var persona = new Persona { Nombre = "Michael Emir" };

        //    //return new ContentResult { Content = $"{persona.Nombre}" };
        //    return Content($"{persona.Nombre}", "text/csv");
        //}

        //EJEMPLO 3:
        //public ActionResult Index()
        //{            
        //    return new FileContentResult(new byte[] { }, "mime type");
        //    //Stream
        //    return new FileStreamResult(new FileStream("", FileMode.Open), "mime type");
        //    //Archivo en disco del servidor
        //    return new FilePathResult("", "mime type");

        //    return File(new byte[] { }, "mime type");
        //}

        //  EJEMPLO 4: LLAMADA AJAX DE LOGIN
        //public ActionResult Index()
        //{
        //    ActionResult result;

        //    if (true) //resultado del logeo
        //    {
        //        result = new HttpStatusCodeResult(HttpStatusCode.Forbidden, "Acceso no permitido.");
        //    }

        //    return result;
        //}

        //EJEMPLOT 5: se redirige a la pagina configurada en el Web.config
        //public ActionResult Index()
        //{
        //    ActionResult result;

        //    if (true) //resultado del logeo
        //    {
        //        //ambos permiten devolver una descripción
        //        result = new HttpUnauthorizedResult("Acceso no permitido.");
        //        result = new HttpNotFoundResult("Recurso no encontrado.");
        //    }

        //    return result;
        //}

        //EJEMPLO 6
        //public ActionResult Index()
        //{
        //    var persona = new Persona { Nombre = "Michael Emir" };

        //    return Json(persona, JsonRequestBehavior.AllowGet); //por motivos de seguridad por defecto no se permiten llamadas GET
        //}

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WAppActionResults/Views/Excel/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>ExcelResult</h2>

@Html.ActionLink("Generar excel", "GenerateExcel", "Excel", new { id = "gen-excel", @class = "btn btn-success" })

@section scripts{
    <script>

        function showLoading(btn) {
            $(btn).attr('disabled', true);
            $(btn).text('Loading...');
        }

        function hideLoading(btn) {
            $(btn).removeAttr('disabled');
            $(btn).text('Generar excel');
        }

        $(function () {
            $('#gen-excel').on('click', function (e) {
                e.preventDefault();

                console.log('Hello World!');
            });
        });
    </script>    
}

WAppActionResults/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WAppActionResults/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WAppActionResults/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

WAppActionResults/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Excel", "Index", "Excel")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>